name: Builds

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      id: node

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        npm install

    - name: Build App
      run: ./node_modules/@angular/cli/bin/ng build --prod

    - name: Dockerize and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: riverfolk/ort-web
        tag_with_ref: true
        tag_with_sha: true
    
    - uses: actions/upload-artifact@v2
      with:
        name: ort-web
        path: ort-web